version: 1.4.0.{build}
image: Visual Studio 2022
install:
#  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
  - echo "starting build"
configuration:
  - Debug
  - Release
cache:
  - packages -> **\packages.config
before_build:
  - cmd: nuget restore
build:
  project: Fossology.Rest.Dotnet.sln
  verbosity: minimal
test: off