version: 1.1.0.{build}
image: Visual Studio 2019
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
configuration:
  - Debug
  - Release
cache:
  - packages -> **\packages.config
before_build:
  - cmd: nuget restore
build:
  project: Fossology.Rest.Dotnet.sln
  verbosity: minimal
test: off